### ISSUE TITLE
Meta-data corresponding to Source and Target for Network construction in Gephi

### ISSUE THREAD

**Issue by vinitamehlawat** [qianjiaqiang/VENAS#2]
Hi @qianjiaqiang 

I have used your repo for construction of evolution network for my sars-cov2 data `Gblocks_Cleaned_sequences.fasta` . In my final outpt I have following files: 

- freq_all.txt
- Gblocks_Cleaned_sequences.ma
- net_all.txt
- nodes_all.txt
- pi_pos_all.fasta
- rm_non-ATCG_genomes.ma
- net.csv
- edgeTable.csv
- nodeTable.csv

Now I wanted to construct the network using Gephi But I am not sure which number you used to construct the source and target, because I want to color the  source node with `State` and target with `city` 

Correct me if I am wrong, I checked manually  in header of some seq ` >hCoV-19/India/MH-C179/2020` and found that `155 is source` for `target 179` means `155 is GJ state` and `179 is MH`state

Please suggest me how to extract the `State` and `City` information for `net.csv` from my raw-data so that I can further plot geo-mapping.

Thanks 
Vinita

**Comment by qianjiaqiang** [comment]
155 means the 155th line in the seq file if my memory isn't wrong.
You can append your  State/city name with the "155"/"179" as a label in Gephi with a csv file as following:
```
155 "State GJ"
...
179 "City MH"
```

@genesisprophet

**Comment by vinitamehlawat** [comment]
Hi @qianjiaqiang 

Thank you for your prompt response 

Could you please suggest which seq file I should look for State/City

1. `pi_pos_all.fasta` & `Gblocks_Cleaned_sequences.ma` which are created after running your script in `example_data folder`
2.  `sequence.fasta` which I used as input fasta file to run VENAS

Thanks
Vinita

**Comment by qianjiaqiang** [comment]
pi_pos_all.fasta

**Comment by vinitamehlawat** [comment]
@qianjiaqiang Thanku very much !

It works for me
